### ISSUE TITLE
Some stuff isn't displaying correctly

### ISSUE THREAD

**Issue by Pondexes** [eesandoval/NefBot#1]
When I type a command (for example ^a nefaria) I get this for the rarity: ":rarity_5::rarity_5::rarity_5::rarity_5::rarity_5:" and this for the element, weapon, and unit type: ":ele_shadow::wep_bow::unit_support:". Everything is working fine.

**Comment by eesandoval** [comment]
This may be an issue with how either the config file having outdated discord ids or an issue fixed in commit f2b2f98. I have released an update including a handful of bugfixes and updates, let me know if this resolves the issue.

**Comment by Pondexes** [comment]
Hm it didn't seem to have fixed it

**Comment by eesandoval** [comment]
Unfortunately these emojis need to be added to a server shared with the bot. I've added instructions to the readme for this along with the assets folder for the emojis used.
